/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;
  
import java.awt.Color;
import java.awt.Font;


    
/**
 *
 * @author tavit
 */
public class PantallaCalculadora extends javax.swing.JFrame {
    String x1;
    String signo;
    String x2;
    /**
     * Creates new form PantallaCalculadora
     */
    public PantallaCalculadora() {
        initComponents();
        
        this.setTitle("CALCULADORA UTH");
        
        Font fuente = new Font("Calibri", 3, 28);
        txtpantalla.setFont(fuente); 
        txtpantalla.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn3 = new javax.swing.JButton();
        btncleanpantalla = new javax.swing.JButton();
        btnpunto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn9 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        puntomenos = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        puntopor = new javax.swing.JButton();
        puntomas = new javax.swing.JButton();
        btnborrarnumero = new javax.swing.JButton();
        txtpantalla = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        neg = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnigual = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btndiventrenumero = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn3.setBackground(new java.awt.Color(153, 0, 153));
        btn3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 228, 84, 57));

        btncleanpantalla.setBackground(new java.awt.Color(255, 0, 204));
        btncleanpantalla.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btncleanpantalla.setForeground(new java.awt.Color(255, 255, 255));
        btncleanpantalla.setText("CE");
        btncleanpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncleanpantallaActionPerformed(evt);
            }
        });
        getContentPane().add(btncleanpantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 90, 55));

        btnpunto.setBackground(new java.awt.Color(255, 0, 204));
        btnpunto.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        btnpunto.setForeground(new java.awt.Color(255, 255, 255));
        btnpunto.setText(".");
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });
        getContentPane().add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 84, 53));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Calculadora UTH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 60));

        btn9.setBackground(new java.awt.Color(153, 0, 153));
        btn9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 356, 84, 56));

        btn6.setBackground(new java.awt.Color(153, 0, 153));
        btn6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 294, 84, 53));

        puntomenos.setBackground(new java.awt.Color(255, 0, 204));
        puntomenos.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        puntomenos.setForeground(new java.awt.Color(255, 255, 255));
        puntomenos.setText("-");
        puntomenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntomenosActionPerformed(evt);
            }
        });
        getContentPane().add(puntomenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 229, 79, 56));

        btndiv.setBackground(new java.awt.Color(255, 0, 204));
        btndiv.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btndiv.setForeground(new java.awt.Color(255, 255, 255));
        btndiv.setText("/");
        btndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivActionPerformed(evt);
            }
        });
        getContentPane().add(btndiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 436, 80, 62));

        puntopor.setBackground(new java.awt.Color(255, 0, 204));
        puntopor.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        puntopor.setForeground(new java.awt.Color(255, 255, 255));
        puntopor.setText("x");
        puntopor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoporActionPerformed(evt);
            }
        });
        getContentPane().add(puntopor, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 364, 80, 56));

        puntomas.setBackground(new java.awt.Color(255, 0, 204));
        puntomas.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        puntomas.setForeground(new java.awt.Color(255, 255, 255));
        puntomas.setText("+");
        puntomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntomasActionPerformed(evt);
            }
        });
        getContentPane().add(puntomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 294, 80, 61));

        btnborrarnumero.setBackground(new java.awt.Color(255, 0, 204));
        btnborrarnumero.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnborrarnumero.setForeground(new java.awt.Color(255, 255, 255));
        btnborrarnumero.setText("C");
        btnborrarnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarnumeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnborrarnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 86, 62));

        txtpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantallaActionPerformed(evt);
            }
        });
        getContentPane().add(txtpantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 89, 427, 70));

        btn1.setBackground(new java.awt.Color(153, 0, 153));
        btn1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 70, 58));

        btn4.setBackground(new java.awt.Color(153, 0, 153));
        btn4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 296, 70, 51));

        btn7.setBackground(new java.awt.Color(153, 0, 153));
        btn7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 356, 70, 56));

        btn0.setBackground(new java.awt.Color(153, 0, 153));
        btn0.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 437, 71, 53));

        btn2.setBackground(new java.awt.Color(153, 0, 153));
        btn2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 228, 83, 57));

        neg.setBackground(new java.awt.Color(255, 0, 204));
        neg.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        neg.setForeground(new java.awt.Color(255, 255, 255));
        neg.setText("Neg/-");
        neg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negActionPerformed(evt);
            }
        });
        getContentPane().add(neg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 437, -1, 53));

        btn8.setBackground(new java.awt.Color(153, 0, 153));
        btn8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 356, 79, 56));

        btnigual.setBackground(new java.awt.Color(255, 0, 204));
        btnigual.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        btnigual.setForeground(new java.awt.Color(255, 255, 255));
        btnigual.setText("=");
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });
        getContentPane().add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 86, 59));

        btn5.setBackground(new java.awt.Color(153, 0, 153));
        btn5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 296, 83, 51));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 60));

        btndiventrenumero.setBackground(new java.awt.Color(255, 0, 204));
        btndiventrenumero.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btndiventrenumero.setForeground(new java.awt.Color(255, 255, 255));
        btndiventrenumero.setText("1/x");
        btndiventrenumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiventrenumeroActionPerformed(evt);
            }
        });
        getContentPane().add(btndiventrenumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 86, 56));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/math.jpg"))); // NOI18N
        imagen.setText("jLabel3");
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 550));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 440, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btncleanpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncleanpantallaActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText("");
    }//GEN-LAST:event_btncleanpantallaActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
        // TODO add your handling code here:

        String cadena=txtpantalla.getText();

        if (cadena.length()<=0) {
            txtpantalla.setText("0.");

        }
        else{
            if (!punto(txtpantalla.getText())) {
                txtpantalla.setText(txtpantalla.getText()+".");

            }
        }

    }//GEN-LAST:event_btnpuntoActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void puntomenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntomenosActionPerformed
        // TODO add your handling code here:
        if (!txtpantalla.getText().equals("")) {
            x1=txtpantalla.getText();
            signo="-";
            txtpantalla.setText("");
        }

    }//GEN-LAST:event_puntomenosActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
        // TODO add your handling code here:
        if (!txtpantalla.getText().equals("")) {
            x1=txtpantalla.getText();
            signo="/";
            txtpantalla.setText("");
        }
    }//GEN-LAST:event_btndivActionPerformed

    private void puntoporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoporActionPerformed
        // TODO add your handling code here:
        if (!txtpantalla.getText().equals("")) {
            x1=txtpantalla.getText();
            signo="*";
            txtpantalla.setText("");
        }
    }//GEN-LAST:event_puntoporActionPerformed

    private void puntomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntomasActionPerformed
        // TODO add your handling code here
        if (!txtpantalla.getText().equals("")) {
            x1=txtpantalla.getText();
            signo="+";
            txtpantalla.setText("");
        }
    }//GEN-LAST:event_puntomasActionPerformed

    private void btnborrarnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarnumeroActionPerformed
        // TODO add your handling code here:
        String cadena;
        cadena=txtpantalla.getText();

        if (cadena.length()>0) {
            cadena=cadena.substring(0, cadena.length()-1);
            txtpantalla.setText(cadena);
        }
    }//GEN-LAST:event_btnborrarnumeroActionPerformed

    private void txtpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantallaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtpantallaActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void negActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negActionPerformed
        // TODO add your handling code here:
        Double num;
        String cadena;
        cadena=txtpantalla.getText();
        if (cadena.length()>0) {
            num=(-1)*Double.parseDouble(cadena);
            txtpantalla.setText(num.toString());
        }
    }//GEN-LAST:event_negActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        // TODO add your handling code here:
        String resultado;
        x2=txtpantalla.getText();

        if (!x2.equals("")) {
            resultado=PantallaCalculadora(x1,x2,signo);
            txtpantalla.setText(resultado);
        }

    }//GEN-LAST:event_btnigualActionPerformed

    public static String PantallaCalculadora(String x1,String x2,String signo){
    Double resultado=0.0;
    String respuesta;
    
    
    if (signo.equals("-")) {
        resultado=Double.parseDouble(x1)-Double.parseDouble(x2);
        
    }
    if (signo.equals("+")) {
        resultado=Double.parseDouble(x1)+Double.parseDouble(x2);
        
    }
    if (signo.equals("*")) {
        resultado=Double.parseDouble(x1)*Double.parseDouble(x2);
        
    }
    if (signo.equals("/")) {
        resultado=Double.parseDouble(x1)/Double.parseDouble(x2);
        
    }
    
    respuesta=resultado.toString();
    return respuesta;
}
    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        txtpantalla.setText(txtpantalla.getText()+"5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btndiventrenumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiventrenumeroActionPerformed
        // TODO add your handling code here:
        String cadena;
        Double num;
        cadena=txtpantalla.getText();
        if (cadena.length()>0) {
            num=1/(Double.parseDouble(cadena));
            txtpantalla.setText(num.toString());

        }
    }//GEN-LAST:event_btndiventrenumeroActionPerformed
 public static boolean punto(String cadena){
        boolean resultado;
        resultado=false;
        
        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.substring(i, i+1).equals(".")) {
                resultado=true;
                break;
                
                
                
                
            }
            
        }
        return resultado;
        
                
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnborrarnumero;
    private javax.swing.JButton btncleanpantalla;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btndiventrenumero;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnpunto;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton neg;
    private javax.swing.JButton puntomas;
    private javax.swing.JButton puntomenos;
    private javax.swing.JButton puntopor;
    private javax.swing.JTextField txtpantalla;
    // End of variables declaration//GEN-END:variables
}
